site_name: Brandon's Simplified Life
site_url: https://ba-calderonmorales.github.io/my-life-as-a-dev/
repo_url: https://github.com/BA-CalderonMorales/my-life-as-a-dev
repo_name: BA-CalderonMorales/my-life-as-a-dev
site_description: >
  A collection of notes, resources, and tools for developers, engineers, and tech enthusiasts.
  This site is a work in progress, so please check back often for updates.

theme:
  name: material
  
  # Custom logo and favicon
  logo: assets/images/me-today.png
  favicon: assets/images/favicon/favicon.ico
  
  # Typography
  font:
    text: Roboto
    code: Fira Code
    
  # Icons
  icon:
    repo: fontawesome/brands/github
    
  # Custom overrides
  custom_dir: docs/overrides
  
  # Hero section
  hero:
    # The image to display in the hero section
    image: assets/images/me-today.png
    # Optional: image size (default: 200px)
    image_size: 200px
    # Optional: image style (default: 'border-radius: 50%')
    image_style: 'border-radius: 50%'
    # Optional: text alignment (default: center)
    align: center
    # Optional: text color (default: white)
    text_color: white
    # Optional: background color (default: primary)
    background_color: primary

  # Theme features
  features:
    - search.suggest
    - search.highlight
    - search.share
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.indexes
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.prune
    - content.code.copy
    - content.code.annotate
    - toc.follow
  
  # Start with dark mode by default
  palette:
    # Dark mode (now listed first to make it default)
    - scheme: slate
      primary: teal
      accent: amber
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    
    # Light mode
    - scheme: default
      primary: teal
      accent: amber
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

markdown_extensions:
  - extra
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.extra
  - pymdownx.tabbed:
      alternate_style: true
  - md_in_html
  - meta
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons

plugins:
  - awesome-nav
  - git-authors:
      show_email_address: true
      href: "mailto:{email}"
  - git-revision-date-localized:
      timezone: America/North_Dakota/Center
  - mike
  - panzoom
  - glightbox
  - print-site
  - search
  - tags
  - ai_plugin
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
          remove_comments: true

# extra_css:

# extra_javascript: