site_name: Brandon's Simplified Life
site_url: https://ba-calderonmorales.github.io/my-life-as-a-dev/
repo_url: https://github.com/BA-CalderonMorales/my-life-as-a-dev
repo_name: BA-CalderonMorales/my-life-as-a-dev
site_description: >
  A collection of notes, resources, and tools for developers, engineers, and tech enthusiasts.
  This site is a work in progress, so please check back often for updates.

theme:
  name: material

  icon:
    repo: fontawesome/brands/github
  
  custom_dir: docs/overrides

  features:
    - search.suggest
    - search.highligt
    - search.share
    - navigation.instant
    - navigation.instang.progress
    - navigation.tracking
    - navigation.indexes
    - navigation.prune
    - navigation.footer
    - content.code.copy
    - content.code.annotate
  
  # Start with dark mode by default
  palette:
    # Dark mode (now listed first to make it default)
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    
    # Light mode
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details

plugins:
  - awesome-nav
  - git-authors:
      show_email_address: true
      href: "mailto:{email}"
  - git-revision-date-localized:
      timezone: America/North_Dakota/Center
  - mike
  - panzoom
  - search
  - tags
  - ai_plugin
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
          remove_comments: true

extra_css:
  - assets/css/custom.css
  - assets/css/components/test-scene-shared.css
  - assets/css/components/dreamscape.css
  - assets/css/components/dreamscape-proto4.css
  - assets/css/components/dreamscape-proto6.css
  - assets/css/components/ghibli-masterpiece.css
  - assets/css/components/color-particle-artifact.css
  - assets/css/components/physics-playground.css
  - assets/css/components/kaleidoscopic-scene.css
  - assets/css/components/intergalactic-scene.css

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/es-module-shims/1.7.3/es-module-shims.min.js
  - { "path": "assets/js/importmap.js", "defer": true }
  - { "path": "assets/js/custom/particleBackground.js", "type": "module" }
  - { "path": "assets/js/custom/initParticles.js", "type": "module" }
  - { "path": "assets/js/custom/versionSelector.js", "type": "module" }
  - { "path": "assets/js/custom/logger.js", "type": "module" }
  - { "path": "assets/js/custom/interactivty-utils.js", "type": "module" }
  - { "path": "assets/js/components/dreamscape/dreamscape.js", "type": "module" }
  - { "path": "assets/js/components/dreamscape-proto4/dreamscape-proto4.js", "type": "module" }
  - { "path": "assets/js/components/dreamscape-proto6/dreamscape-proto6.js", "type": "module" }
  - { "path": "assets/js/components/ghibli-masterpiece/ghibli-masterpiece.js", "type": "module" }
  - { "path": "assets/js/components/color-particle-artifact/color-particle-artifact.js", "type": "module" }
  - { "path": "assets/js/components/physics-playground/physics-playground.js", "type": "module" }
  - { "path": "assets/js/components/kaleidoscopic-scene/kaleidoscopic-scene.js", "type": "module" }
  - { "path": "assets/js/components/intergalactic-scene/intergalactic-scene.js", "type": "module" }

extra:
  version:
    provider: mike
    default: latest
    json_file: versions.json