# ==============================================================================
# SITE IDENTITY
# ==============================================================================

[project]
site_name = "Brandon A. Calderon Morales"
site_description = "Engineer and Marine veteran in Omaha, Nebraska."
site_author = "Brandon A. Calderon Morales"
site_url = "https://ba-calderonmorales.github.io/my-life-as-a-dev/"
copyright = "Copyright &copy; 2024-2026 Brandon A. Calderon Morales"
repo_url = "https://github.com/BA-CalderonMorales/my-life-as-a-dev"
repo_name = "BA-CalderonMorales/my-life-as-a-dev"
edit_uri = "edit/main/docs/"
