# ==============================================================================
# PLUGINS
# ==============================================================================
# Quiet git metadata. Nothing else.
# ==============================================================================

[project.plugins.git-authors]
enabled = true
show_email_address = true
href = "mailto:{email}"

[project.plugins.git-revision-date-localized]
timezone = "America/North_Dakota/Center"
