ignore:

  - docs/overrides
  - scripts
  - .gitignore
  - .git
  - .github
  - requirements.txt
  - LICENSE
  - README.md
  - mkdocs.yml

nav:

  - Home: index.md

  - interests

  - repositories

  - blog
