ignore:

  - docs/overrides
  - scripts
  - .gitignore
  - .git
  - .github
  - requirements.txt
  - LICENSE
  - README.md
  - mkdocs.yml

nav:

  - Home: index.md

  - Projects: projects/index.md

  - Repositories: repositories/index.md

  - Docs-as-Code: docs-as-code/index.md
