ignore:

  - docs/overrides
  - scripts
  - .gitignore
  - .git
  - .github
  - requirements.txt
  - LICENSE
  - README.md
  - mkdocs.yml

nav:

  - Home: index.md

  - Projects: projects/index.md

  - Repositories:

    - Overview: repositories/index.md

    - My Life as a Dev:
      - Overview: repositories/my-life-as-a-dev/index.md
      - Quick Start: repositories/my-life-as-a-dev/quick_start/index.md
      - Details: repositories/my-life-as-a-dev/details/index.md

    - Immersive Awe Canvas:
      - Overview: repositories/immersive-awe-canvas/index.md
      - Quick Start: repositories/immersive-awe-canvas/quick_start/index.md
      - Details: repositories/immersive-awe-canvas/details/index.md

    - Shadow Scroll Blossom:
      - Overview: repositories/shadow-scroll-blossom/index.md
      - Quick Start: repositories/shadow-scroll-blossom/quick_start/index.md
      - Details: repositories/shadow-scroll-blossom/details/index.md

    - Rust Terminal Forge:
      - Overview: repositories/rust-terminal-forge/index.md
      - Quick Start: repositories/rust-terminal-forge/quick_start/index.md
      - Details: repositories/rust-terminal-forge/details/index.md

  - Docs-as-Code: docs-as-code/index.md
