name: AI Plugin Integration

on:
  push:
    paths:
      - 'mkdocs_plugins/ai_plugin.py'
      - 'docs/ai-demo.md'
      - 'requirements.txt'
      - 'mkdocs.yml'
  pull_request:
    paths:
      - 'mkdocs_plugins/ai_plugin.py'
      - 'docs/ai-demo.md'
      - 'requirements.txt'
      - 'mkdocs.yml'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          sparse-checkout: |
            docs
            mkdocs_plugins
            
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: pip
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 pytest
          
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 mkdocs_plugins/ --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings
          flake8 mkdocs_plugins/ --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
          
      - name: Validate plugin loads correctly
        run: |
          # Test if mkdocs can load the configuration with the AI plugin
          mkdocs build --strict
          
      - name: Check if AI demo page builds
        run: |
          # Verify that the AI demo page exists in the built site
          test -f ./site/ai-demo/index.html || (echo "AI Demo page not found in build!" && exit 1)