name: Deploy MkDocs to GitHub Pages

on:

  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: write 
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: pages
  cancel-in-progress: true

jobs:

  # Job # 1: Build MkDocs site
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          
          # to accommodate last update with mkdocs.yml plugin -> mkdocs-git-revision-date-localised-plugin
          fetch-depth: 0

          # help with speed up of docs builds: https://x.com/squidfunk/status/1705279829770150291
          sparse-checkout: |
            docs
            includes

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: pip

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build MkDocs site
        run: mkdocs build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./site

  # Job # 2: Deploy to GitHub Pages
  deploy:

    needs: build

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mike

      - name: Setup Git User
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Deploy with mike
        run: |
          LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "0.0.1")
          echo "Using version: $LATEST_TAG"
          mike deploy --push --update-aliases $LATEST_TAG latest