name: Deploy MkDocs to GitHub Pages

on:

  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: write  # Needed for mike to commit to gh-pages branch
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: pages
  cancel-in-progress: true

jobs:

  # Job # 1: Build MkDocs site with versioning
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # Fetch complete history for proper versioning
          fetch-depth: 0

          # help with speed up of docs builds: https://x.com/squidfunk/status/1705279829770150291
          sparse-checkout: |
            docs
            mkdocs_plugins
            mkdocs.yml
            setup.py
            requirements.txt
            
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: pip

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

          # Install local plugin in development mode
          pip install -e .

      - name: Configure Git for Mike
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Get latest version tag
        id: get-latest-tag
        run: |
          # Get the latest tag or use "0.1.0" if no tags exist
          LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "0.1.0")
          echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV
          echo "Latest tag: $LATEST_TAG"

      - name: Build and deploy with Mike
        run: |
          # Explicitly verify plugin module is available
          python -c "import sys; import mkdocs_plugins; print(f'Plugin module found at: {mkdocs_plugins.__file__}')"
          
          # Set PYTHONPATH to include the local plugins
          export PYTHONPATH=$PYTHONPATH:$(pwd)
          
          # Deploy the latest version with Mike
          mike deploy --push $LATEST_TAG latest
          
          # This is the critical step: Set the default version AFTER deploy
          mike set-default --push latest
          
          # List versions to verify
          mike list

      - name: Build site with MkDocs
        run: |
          # Set PYTHONPATH to include the local plugins
          export PYTHONPATH=$PYTHONPATH:$(pwd)
          
          # Build the site with MkDocs
          mkdocs build

      - name: Ensure versions.json is in the right place
        run: |
          # Make sure versions.json exists in the site root for GitHub Pages
          mike list --json > site/versions.json
          
          # Verify versions.json was created correctly
          echo "Contents of versions.json:"
          cat site/versions.json
          
          # Create a .nojekyll file to prevent GitHub Pages from ignoring files
          touch site/.nojekyll

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./site

  # Job # 2: Deploy to GitHub Pages
  deploy:

    needs: build

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4