name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write 
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  # Job # 1: Install Dependencies
  install_dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            requirements.txt

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: pip

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install mike
          # Create a marker file that includes pip freeze output
          pip freeze > installed_packages.txt

      - name: Cache Python dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}-${{ hashFiles('**/installed_packages.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Upload dependency artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-env
          path: |
            ~/.cache/pip
            installed_packages.txt

  # Job # 2: Build MkDocs site
  build:
    needs: install_dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # Full history for git plugins
          fetch-depth: 0
          # Speed up builds
          sparse-checkout: |
            docs
            includes
            mkdocs.yml
            requirements.txt

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: pip

      - name: Download dependency artifact
        uses: actions/download-artifact@v4
        with:
          name: python-env

      - name: Restore dependency cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}-${{ hashFiles('**/installed_packages.txt') }}

      - name: Reinstall dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build MkDocs site
        run: mkdocs build

      - name: Upload built site
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./site

  # Job # 3: Deploy to GitHub Pages
  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Download dependency artifact
        uses: actions/download-artifact@v4
        with:
          name: python-env

      - name: Restore dependency cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}-${{ hashFiles('**/installed_packages.txt') }}

      - name: Install mike
        run: |
          python -m pip install --upgrade pip
          pip install mike

      - name: Setup Git User
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Deploy with mike
        run: |
          LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "0.0.1")
          echo "Using version: $LATEST_TAG"
          mike deploy --push --update-aliases $LATEST_TAG latest