name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write 
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  # Job # 1: Install Dependencies
  install_dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            requirements.txt

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: pip

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install mike
          # Create a marker file that includes pip freeze output
          pip freeze > installed_packages.txt

      - name: Cache Python dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}-${{ hashFiles('**/installed_packages.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Upload dependency artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-env
          path: |
            ~/.cache/pip
            installed_packages.txt

  # Job # 2: Build and Deploy with Mike
  deploy:
    needs: install_dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # Full history for git plugins
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: pip

      - name: Download dependency artifact
        uses: actions/download-artifact@v4
        with:
          name: python-env

      - name: Restore dependency cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}-${{ hashFiles('**/installed_packages.txt') }}

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install mike

      - name: Configure Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          # Install jq for versions.json manipulation
          sudo apt-get install jq -y

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v4
      
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4